// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mytc/relay/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryEndpointRequest struct {
	OperatorAddr string `protobuf:"bytes,1,opt,name=operator_addr,json=operatorAddr,proto3" json:"operator_addr,omitempty"`
}

func (m *QueryEndpointRequest) Reset()         { *m = QueryEndpointRequest{} }
func (m *QueryEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEndpointRequest) ProtoMessage()    {}
func (*QueryEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52171d20e6879785, []int{0}
}
func (m *QueryEndpointRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEndpointRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEndpointRequest.Merge(m, src)
}
func (m *QueryEndpointRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEndpointRequest proto.InternalMessageInfo

func (m *QueryEndpointRequest) GetOperatorAddr() string {
	if m != nil {
		return m.OperatorAddr
	}
	return ""
}

type QueryEndpointResponse struct {
	Endpoint *RelayEndpoint `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
}

func (m *QueryEndpointResponse) Reset()         { *m = QueryEndpointResponse{} }
func (m *QueryEndpointResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEndpointResponse) ProtoMessage()    {}
func (*QueryEndpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52171d20e6879785, []int{1}
}
func (m *QueryEndpointResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEndpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEndpointResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEndpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEndpointResponse.Merge(m, src)
}
func (m *QueryEndpointResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEndpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEndpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEndpointResponse proto.InternalMessageInfo

func (m *QueryEndpointResponse) GetEndpoint() *RelayEndpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type QueryEndpointsRequest struct {
	MaxStaleSeconds int64              `protobuf:"varint,1,opt,name=max_stale_seconds,json=maxStaleSeconds,proto3" json:"max_stale_seconds,omitempty"`
	Pagination      *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryEndpointsRequest) Reset()         { *m = QueryEndpointsRequest{} }
func (m *QueryEndpointsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEndpointsRequest) ProtoMessage()    {}
func (*QueryEndpointsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52171d20e6879785, []int{2}
}
func (m *QueryEndpointsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEndpointsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEndpointsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEndpointsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEndpointsRequest.Merge(m, src)
}
func (m *QueryEndpointsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEndpointsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEndpointsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEndpointsRequest proto.InternalMessageInfo

func (m *QueryEndpointsRequest) GetMaxStaleSeconds() int64 {
	if m != nil {
		return m.MaxStaleSeconds
	}
	return 0
}

func (m *QueryEndpointsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryEndpointsResponse struct {
	Endpoints  []*RelayEndpoint    `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryEndpointsResponse) Reset()         { *m = QueryEndpointsResponse{} }
func (m *QueryEndpointsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEndpointsResponse) ProtoMessage()    {}
func (*QueryEndpointsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52171d20e6879785, []int{3}
}
func (m *QueryEndpointsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEndpointsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEndpointsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEndpointsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEndpointsResponse.Merge(m, src)
}
func (m *QueryEndpointsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEndpointsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEndpointsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEndpointsResponse proto.InternalMessageInfo

func (m *QueryEndpointsResponse) GetEndpoints() []*RelayEndpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *QueryEndpointsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryEndpointRequest)(nil), "mytc.relay.v1.QueryEndpointRequest")
	proto.RegisterType((*QueryEndpointResponse)(nil), "mytc.relay.v1.QueryEndpointResponse")
	proto.RegisterType((*QueryEndpointsRequest)(nil), "mytc.relay.v1.QueryEndpointsRequest")
	proto.RegisterType((*QueryEndpointsResponse)(nil), "mytc.relay.v1.QueryEndpointsResponse")
}

func init() { proto.RegisterFile("mytc/relay/v1/query.proto", fileDescriptor_52171d20e6879785) }

var fileDescriptor_52171d20e6879785 = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x73, 0xa9, 0x40, 0xcd, 0x41, 0x85, 0x38, 0x15, 0x14, 0xac, 0xca, 0xaa, 0x5c, 0x68,
	0xa1, 0xc3, 0x9d, 0x52, 0x16, 0x04, 0x0b, 0x20, 0x01, 0x2b, 0x75, 0x37, 0x96, 0xe8, 0x12, 0x9f,
	0x5c, 0x4b, 0xf1, 0x3d, 0xf7, 0xee, 0x12, 0xc5, 0x20, 0x16, 0x06, 0x16, 0x18, 0x90, 0x98, 0xf9,
	0x3e, 0x8c, 0x95, 0x58, 0x18, 0x51, 0xc2, 0x07, 0x41, 0x77, 0x67, 0xa7, 0x8d, 0x55, 0x92, 0xcd,
	0x7a, 0xef, 0xff, 0xfe, 0xef, 0xf7, 0xde, 0x3b, 0xe3, 0x7b, 0x79, 0x69, 0x86, 0x4c, 0x89, 0x11,
	0x2f, 0xd9, 0xa4, 0xc7, 0xce, 0xc6, 0x42, 0x95, 0xb4, 0x50, 0x60, 0x80, 0x6c, 0xd9, 0x14, 0x75,
	0x29, 0x3a, 0xe9, 0x05, 0xdb, 0x29, 0xa4, 0xe0, 0x32, 0xcc, 0x7e, 0x79, 0x51, 0xb0, 0x93, 0x02,
	0xa4, 0x23, 0xc1, 0x78, 0x91, 0x31, 0x2e, 0x25, 0x18, 0x6e, 0x32, 0x90, 0xba, 0xca, 0x36, 0xdc,
	0xbd, 0x97, 0x4f, 0x1d, 0x0e, 0x41, 0xe7, 0xa0, 0xd9, 0x80, 0x6b, 0xe1, 0xdb, 0xb2, 0x49, 0x6f,
	0x20, 0x0c, 0xef, 0xb1, 0x82, 0xa7, 0x99, 0x74, 0x3e, 0x5e, 0x1b, 0x3d, 0xc3, 0xdb, 0xc7, 0x56,
	0xf1, 0x4a, 0x26, 0x05, 0x64, 0xd2, 0xc4, 0xe2, 0x6c, 0x2c, 0xb4, 0x21, 0x7b, 0x78, 0x0b, 0x0a,
	0xa1, 0xb8, 0x01, 0xd5, 0xe7, 0x49, 0xa2, 0xba, 0x68, 0x17, 0x3d, 0xec, 0xc4, 0x37, 0xeb, 0xe0,
	0x8b, 0x24, 0x51, 0xd1, 0x31, 0xbe, 0xd3, 0x28, 0xd6, 0x05, 0x48, 0x2d, 0xc8, 0x13, 0xbc, 0x29,
	0xaa, 0x98, 0x2b, 0xbc, 0x71, 0xb4, 0x43, 0x97, 0x46, 0xa6, 0xb1, 0xfd, 0x58, 0xd4, 0x2d, 0xd4,
	0xd1, 0x17, 0xd4, 0xf0, 0xd4, 0x35, 0xd1, 0x21, 0xbe, 0x9d, 0xf3, 0x69, 0x5f, 0x1b, 0x3e, 0x12,
	0x7d, 0x2d, 0x86, 0x20, 0x13, 0xed, 0xcc, 0x37, 0xe2, 0x5b, 0x39, 0x9f, 0x9e, 0xd8, 0xf8, 0x89,
	0x0f, 0x93, 0xd7, 0x18, 0x5f, 0x4c, 0xda, 0x6d, 0x3b, 0x82, 0x7d, 0xea, 0xd7, 0x42, 0xed, 0x5a,
	0xa8, 0xbf, 0x46, 0xb5, 0x16, 0xfa, 0x96, 0xa7, 0xa2, 0xea, 0x13, 0x5f, 0xaa, 0x8c, 0x7e, 0x20,
	0x7c, 0xb7, 0x49, 0x53, 0x8d, 0xf8, 0x14, 0x77, 0x6a, 0x68, 0x8b, 0xb1, 0xb1, 0x76, 0xc6, 0x0b,
	0x39, 0x79, 0x73, 0x05, 0xde, 0xc1, 0x5a, 0x3c, 0xdf, 0xf8, 0x32, 0xdf, 0xd1, 0xd7, 0x36, 0xbe,
	0xe6, 0xf8, 0xc8, 0x67, 0x84, 0x37, 0xeb, 0x56, 0x64, 0xaf, 0x01, 0x72, 0xd5, 0x85, 0x83, 0xfb,
	0xab, 0x45, 0xbe, 0x5b, 0xc4, 0x3e, 0xfd, 0xfa, 0xfb, 0xbd, 0xfd, 0x88, 0x1c, 0xb0, 0xe5, 0xf7,
	0x56, 0x0f, 0xc3, 0x3e, 0x2c, 0x3d, 0x93, 0x8f, 0xe4, 0x3d, 0xee, 0x2c, 0x96, 0x45, 0x56, 0xf6,
	0xa8, 0x2f, 0x1b, 0x3c, 0x58, 0xa3, 0xaa, 0x50, 0x76, 0x1d, 0x4a, 0x40, 0xba, 0xff, 0x41, 0xd1,
	0x2f, 0x9f, 0xff, 0x9c, 0x85, 0xe8, 0x7c, 0x16, 0xa2, 0x3f, 0xb3, 0x10, 0x7d, 0x9b, 0x87, 0xad,
	0xf3, 0x79, 0xd8, 0xfa, 0x3d, 0x0f, 0x5b, 0xef, 0xf6, 0xd3, 0xcc, 0x9c, 0x8e, 0x07, 0x74, 0x08,
	0xb9, 0xad, 0x3e, 0x15, 0x4a, 0x71, 0x6f, 0x33, 0xad, 0x8c, 0x4c, 0x59, 0x08, 0x3d, 0xb8, 0xee,
	0xfe, 0x8a, 0xc7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x79, 0xf5, 0x44, 0x3c, 0xbc, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Endpoint queries a single relay endpoint by validator operator address.
	Endpoint(ctx context.Context, in *QueryEndpointRequest, opts ...grpc.CallOption) (*QueryEndpointResponse, error)
	// Endpoints queries every registered relay endpoint, optionally filtered by
	// staleness (max_stale_seconds — 0 means no filter).
	Endpoints(ctx context.Context, in *QueryEndpointsRequest, opts ...grpc.CallOption) (*QueryEndpointsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Endpoint(ctx context.Context, in *QueryEndpointRequest, opts ...grpc.CallOption) (*QueryEndpointResponse, error) {
	out := new(QueryEndpointResponse)
	err := c.cc.Invoke(ctx, "/mytc.relay.v1.Query/Endpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Endpoints(ctx context.Context, in *QueryEndpointsRequest, opts ...grpc.CallOption) (*QueryEndpointsResponse, error) {
	out := new(QueryEndpointsResponse)
	err := c.cc.Invoke(ctx, "/mytc.relay.v1.Query/Endpoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Endpoint queries a single relay endpoint by validator operator address.
	Endpoint(context.Context, *QueryEndpointRequest) (*QueryEndpointResponse, error)
	// Endpoints queries every registered relay endpoint, optionally filtered by
	// staleness (max_stale_seconds — 0 means no filter).
	Endpoints(context.Context, *QueryEndpointsRequest) (*QueryEndpointsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Endpoint(ctx context.Context, req *QueryEndpointRequest) (*QueryEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Endpoint not implemented")
}
func (*UnimplementedQueryServer) Endpoints(ctx context.Context, req *QueryEndpointsRequest) (*QueryEndpointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Endpoints not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Endpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Endpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mytc.relay.v1.Query/Endpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Endpoint(ctx, req.(*QueryEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Endpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Endpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mytc.relay.v1.Query/Endpoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Endpoints(ctx, req.(*QueryEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mytc.relay.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Endpoint",
			Handler:    _Query_Endpoint_Handler,
		},
		{
			MethodName: "Endpoints",
			Handler:    _Query_Endpoints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mytc/relay/v1/query.proto",
}

func (m *QueryEndpointRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEndpointRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEndpointRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OperatorAddr) > 0 {
		i -= len(m.OperatorAddr)
		copy(dAtA[i:], m.OperatorAddr)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.OperatorAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEndpointResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEndpointResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEndpointResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Endpoint != nil {
		{
			size, err := m.Endpoint.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEndpointsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEndpointsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEndpointsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.MaxStaleSeconds != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.MaxStaleSeconds))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryEndpointsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEndpointsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEndpointsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Endpoints) > 0 {
		for iNdEx := len(m.Endpoints) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Endpoints[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryEndpointRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddr)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEndpointResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Endpoint != nil {
		l = m.Endpoint.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEndpointsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxStaleSeconds != 0 {
		n += 1 + sovQuery(uint64(m.MaxStaleSeconds))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEndpointsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Endpoints) > 0 {
		for _, e := range m.Endpoints {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryEndpointRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEndpointRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEndpointRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEndpointResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEndpointResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEndpointResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Endpoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Endpoint == nil {
				m.Endpoint = &RelayEndpoint{}
			}
			if err := m.Endpoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEndpointsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEndpointsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEndpointsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxStaleSeconds", wireType)
			}
			m.MaxStaleSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxStaleSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEndpointsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEndpointsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEndpointsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Endpoints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Endpoints = append(m.Endpoints, &RelayEndpoint{})
			if err := m.Endpoints[len(m.Endpoints)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
