// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mytc/relay/v1/relay.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RelayEndpoint is a validator's published relay-server WSS URL.
type RelayEndpoint struct {
	OperatorAddr  string `protobuf:"bytes,1,opt,name=operator_addr,json=operatorAddr,proto3" json:"operator_addr,omitempty"`
	WssUrl        string `protobuf:"bytes,2,opt,name=wss_url,json=wssUrl,proto3" json:"wss_url,omitempty"`
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	LastHeartbeat int64  `protobuf:"varint,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	RegisteredAt  int64  `protobuf:"varint,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
}

func (m *RelayEndpoint) Reset()         { *m = RelayEndpoint{} }
func (m *RelayEndpoint) String() string { return proto.CompactTextString(m) }
func (*RelayEndpoint) ProtoMessage()    {}
func (*RelayEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f3af08ede863885, []int{0}
}
func (m *RelayEndpoint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RelayEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RelayEndpoint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RelayEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayEndpoint.Merge(m, src)
}
func (m *RelayEndpoint) XXX_Size() int {
	return m.Size()
}
func (m *RelayEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_RelayEndpoint proto.InternalMessageInfo

func (m *RelayEndpoint) GetOperatorAddr() string {
	if m != nil {
		return m.OperatorAddr
	}
	return ""
}

func (m *RelayEndpoint) GetWssUrl() string {
	if m != nil {
		return m.WssUrl
	}
	return ""
}

func (m *RelayEndpoint) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *RelayEndpoint) GetLastHeartbeat() int64 {
	if m != nil {
		return m.LastHeartbeat
	}
	return 0
}

func (m *RelayEndpoint) GetRegisteredAt() int64 {
	if m != nil {
		return m.RegisteredAt
	}
	return 0
}

func init() {
	proto.RegisterType((*RelayEndpoint)(nil), "mytc.relay.v1.RelayEndpoint")
}

func init() { proto.RegisterFile("mytc/relay/v1/relay.proto", fileDescriptor_7f3af08ede863885) }

var fileDescriptor_7f3af08ede863885 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xc1, 0x4a, 0xf4, 0x30,
	0x14, 0x85, 0x9b, 0x7f, 0x7e, 0x67, 0x30, 0x4c, 0x5d, 0x14, 0xc1, 0xe8, 0x22, 0x0c, 0x8a, 0x32,
	0xab, 0x96, 0xc1, 0x17, 0x70, 0x04, 0xc1, 0x75, 0xc1, 0x8d, 0x9b, 0x92, 0x4e, 0x42, 0x5b, 0x68,
	0x9b, 0x72, 0x73, 0xa7, 0x63, 0xdf, 0xc2, 0x77, 0xf1, 0x25, 0x5c, 0xce, 0xd2, 0xa5, 0xb4, 0x2f,
	0x22, 0x49, 0x2d, 0xee, 0x4e, 0xbe, 0xef, 0x40, 0xb8, 0x87, 0x5e, 0x56, 0x1d, 0xee, 0x22, 0x50,
	0xa5, 0xe8, 0xa2, 0x76, 0x33, 0x86, 0xb0, 0x01, 0x8d, 0x3a, 0xf0, 0xad, 0x0a, 0x47, 0xd2, 0x6e,
	0xae, 0xce, 0x33, 0x9d, 0x69, 0x67, 0x22, 0x9b, 0xc6, 0xd2, 0xf5, 0x07, 0xa1, 0x7e, 0x6c, 0x2b,
	0x4f, 0xb5, 0x6c, 0x74, 0x51, 0x63, 0x70, 0x43, 0x7d, 0xdd, 0x28, 0x10, 0xa8, 0x21, 0x11, 0x52,
	0x02, 0x23, 0x2b, 0xb2, 0x3e, 0x8d, 0x97, 0x13, 0xdc, 0x4a, 0x09, 0xc1, 0x05, 0x5d, 0x1c, 0x8c,
	0x49, 0xf6, 0x50, 0xb2, 0x7f, 0x4e, 0xcf, 0x0f, 0xc6, 0xbc, 0x40, 0x19, 0x30, 0xba, 0x68, 0x15,
	0x98, 0x42, 0xd7, 0x6c, 0xe6, 0xc4, 0xf4, 0x0c, 0x6e, 0xe9, 0x59, 0x29, 0x0c, 0x26, 0xb9, 0x12,
	0x80, 0xa9, 0x12, 0xc8, 0xfe, 0xaf, 0xc8, 0x7a, 0x16, 0xfb, 0x96, 0x3e, 0x4f, 0xd0, 0x7e, 0x0f,
	0x2a, 0x2b, 0x0c, 0x2a, 0x50, 0x32, 0x11, 0xc8, 0x4e, 0x5c, 0x6b, 0xf9, 0x07, 0xb7, 0xf8, 0xf8,
	0xf0, 0xd9, 0x73, 0x72, 0xec, 0x39, 0xf9, 0xee, 0x39, 0x79, 0x1f, 0xb8, 0x77, 0x1c, 0xb8, 0xf7,
	0x35, 0x70, 0xef, 0xf5, 0x2e, 0x2b, 0x30, 0xdf, 0xa7, 0xe1, 0x4e, 0x57, 0x51, 0xd5, 0x61, 0xae,
	0x00, 0x44, 0xe4, 0x36, 0x7a, 0xfb, 0x5d, 0x09, 0xbb, 0x46, 0x99, 0x74, 0xee, 0xce, 0xbf, 0xff,
	0x09, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xa0, 0x76, 0xd0, 0x40, 0x01, 0x00, 0x00,
}

func (m *RelayEndpoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RelayEndpoint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RelayEndpoint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RegisteredAt != 0 {
		i = encodeVarintRelay(dAtA, i, uint64(m.RegisteredAt))
		i--
		dAtA[i] = 0x28
	}
	if m.LastHeartbeat != 0 {
		i = encodeVarintRelay(dAtA, i, uint64(m.LastHeartbeat))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.WssUrl) > 0 {
		i -= len(m.WssUrl)
		copy(dAtA[i:], m.WssUrl)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.WssUrl)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OperatorAddr) > 0 {
		i -= len(m.OperatorAddr)
		copy(dAtA[i:], m.OperatorAddr)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.OperatorAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRelay(dAtA []byte, offset int, v uint64) int {
	offset -= sovRelay(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RelayEndpoint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddr)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	l = len(m.WssUrl)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	if m.LastHeartbeat != 0 {
		n += 1 + sovRelay(uint64(m.LastHeartbeat))
	}
	if m.RegisteredAt != 0 {
		n += 1 + sovRelay(uint64(m.RegisteredAt))
	}
	return n
}

func sovRelay(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRelay(x uint64) (n int) {
	return sovRelay(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RelayEndpoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRelay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RelayEndpoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RelayEndpoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WssUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WssUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastHeartbeat", wireType)
			}
			m.LastHeartbeat = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastHeartbeat |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredAt", wireType)
			}
			m.RegisteredAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegisteredAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRelay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRelay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRelay(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRelay
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRelay
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRelay
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRelay
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRelay        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRelay          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRelay = fmt.Errorf("proto: unexpected end of group")
)
