// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mytc/relay/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterRelay struct {
	OperatorAddr string `protobuf:"bytes,1,opt,name=operator_addr,json=operatorAddr,proto3" json:"operator_addr,omitempty"`
	WssUrl       string `protobuf:"bytes,2,opt,name=wss_url,json=wssUrl,proto3" json:"wss_url,omitempty"`
	Version      string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *MsgRegisterRelay) Reset()         { *m = MsgRegisterRelay{} }
func (m *MsgRegisterRelay) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterRelay) ProtoMessage()    {}
func (*MsgRegisterRelay) Descriptor() ([]byte, []int) {
	return fileDescriptor_5163989571b83ebf, []int{0}
}
func (m *MsgRegisterRelay) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterRelay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterRelay.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterRelay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterRelay.Merge(m, src)
}
func (m *MsgRegisterRelay) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterRelay) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterRelay.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterRelay proto.InternalMessageInfo

func (m *MsgRegisterRelay) GetOperatorAddr() string {
	if m != nil {
		return m.OperatorAddr
	}
	return ""
}

func (m *MsgRegisterRelay) GetWssUrl() string {
	if m != nil {
		return m.WssUrl
	}
	return ""
}

func (m *MsgRegisterRelay) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type MsgRegisterRelayResponse struct {
}

func (m *MsgRegisterRelayResponse) Reset()         { *m = MsgRegisterRelayResponse{} }
func (m *MsgRegisterRelayResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterRelayResponse) ProtoMessage()    {}
func (*MsgRegisterRelayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5163989571b83ebf, []int{1}
}
func (m *MsgRegisterRelayResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterRelayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterRelayResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterRelayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterRelayResponse.Merge(m, src)
}
func (m *MsgRegisterRelayResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterRelayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterRelayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterRelayResponse proto.InternalMessageInfo

type MsgUnregisterRelay struct {
	OperatorAddr string `protobuf:"bytes,1,opt,name=operator_addr,json=operatorAddr,proto3" json:"operator_addr,omitempty"`
}

func (m *MsgUnregisterRelay) Reset()         { *m = MsgUnregisterRelay{} }
func (m *MsgUnregisterRelay) String() string { return proto.CompactTextString(m) }
func (*MsgUnregisterRelay) ProtoMessage()    {}
func (*MsgUnregisterRelay) Descriptor() ([]byte, []int) {
	return fileDescriptor_5163989571b83ebf, []int{2}
}
func (m *MsgUnregisterRelay) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnregisterRelay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnregisterRelay.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnregisterRelay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnregisterRelay.Merge(m, src)
}
func (m *MsgUnregisterRelay) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnregisterRelay) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnregisterRelay.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnregisterRelay proto.InternalMessageInfo

func (m *MsgUnregisterRelay) GetOperatorAddr() string {
	if m != nil {
		return m.OperatorAddr
	}
	return ""
}

type MsgUnregisterRelayResponse struct {
}

func (m *MsgUnregisterRelayResponse) Reset()         { *m = MsgUnregisterRelayResponse{} }
func (m *MsgUnregisterRelayResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUnregisterRelayResponse) ProtoMessage()    {}
func (*MsgUnregisterRelayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5163989571b83ebf, []int{3}
}
func (m *MsgUnregisterRelayResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnregisterRelayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnregisterRelayResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnregisterRelayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnregisterRelayResponse.Merge(m, src)
}
func (m *MsgUnregisterRelayResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnregisterRelayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnregisterRelayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnregisterRelayResponse proto.InternalMessageInfo

type MsgHeartbeat struct {
	OperatorAddr string `protobuf:"bytes,1,opt,name=operator_addr,json=operatorAddr,proto3" json:"operator_addr,omitempty"`
}

func (m *MsgHeartbeat) Reset()         { *m = MsgHeartbeat{} }
func (m *MsgHeartbeat) String() string { return proto.CompactTextString(m) }
func (*MsgHeartbeat) ProtoMessage()    {}
func (*MsgHeartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_5163989571b83ebf, []int{4}
}
func (m *MsgHeartbeat) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgHeartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgHeartbeat.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgHeartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgHeartbeat.Merge(m, src)
}
func (m *MsgHeartbeat) XXX_Size() int {
	return m.Size()
}
func (m *MsgHeartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgHeartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_MsgHeartbeat proto.InternalMessageInfo

func (m *MsgHeartbeat) GetOperatorAddr() string {
	if m != nil {
		return m.OperatorAddr
	}
	return ""
}

type MsgHeartbeatResponse struct {
}

func (m *MsgHeartbeatResponse) Reset()         { *m = MsgHeartbeatResponse{} }
func (m *MsgHeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*MsgHeartbeatResponse) ProtoMessage()    {}
func (*MsgHeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5163989571b83ebf, []int{5}
}
func (m *MsgHeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgHeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgHeartbeatResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgHeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgHeartbeatResponse.Merge(m, src)
}
func (m *MsgHeartbeatResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgHeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgHeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgHeartbeatResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterRelay)(nil), "mytc.relay.v1.MsgRegisterRelay")
	proto.RegisterType((*MsgRegisterRelayResponse)(nil), "mytc.relay.v1.MsgRegisterRelayResponse")
	proto.RegisterType((*MsgUnregisterRelay)(nil), "mytc.relay.v1.MsgUnregisterRelay")
	proto.RegisterType((*MsgUnregisterRelayResponse)(nil), "mytc.relay.v1.MsgUnregisterRelayResponse")
	proto.RegisterType((*MsgHeartbeat)(nil), "mytc.relay.v1.MsgHeartbeat")
	proto.RegisterType((*MsgHeartbeatResponse)(nil), "mytc.relay.v1.MsgHeartbeatResponse")
}

func init() { proto.RegisterFile("mytc/relay/v1/tx.proto", fileDescriptor_5163989571b83ebf) }

var fileDescriptor_5163989571b83ebf = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcb, 0x4e, 0xc2, 0x40,
	0x14, 0xa5, 0x90, 0x40, 0xb8, 0x81, 0x68, 0x26, 0x04, 0x9b, 0x6a, 0xaa, 0x96, 0xc4, 0xc7, 0xa6,
	0x0d, 0xb2, 0x72, 0xa7, 0xae, 0xdc, 0x74, 0xd3, 0x84, 0x85, 0x6e, 0x48, 0xa1, 0x93, 0x01, 0x03,
	0x4c, 0x73, 0xef, 0xf0, 0xe8, 0x5f, 0xf0, 0x59, 0x2e, 0x59, 0xba, 0x34, 0xf0, 0x23, 0x86, 0x6a,
	0x51, 0xda, 0x44, 0x74, 0x37, 0x73, 0xcf, 0xe3, 0xce, 0x9c, 0x1c, 0xa8, 0x8f, 0x22, 0xd5, 0x73,
	0x90, 0x0f, 0xfd, 0xc8, 0x99, 0x36, 0x1d, 0x35, 0xb7, 0x43, 0x94, 0x4a, 0xb2, 0xea, 0x66, 0x6e,
	0xc7, 0x73, 0x7b, 0xda, 0x34, 0x6a, 0x42, 0x0a, 0x19, 0x23, 0xce, 0xe6, 0xf4, 0x49, 0xb2, 0x5e,
	0xe0, 0xd0, 0x25, 0xe1, 0x71, 0x31, 0x20, 0xc5, 0xd1, 0xdb, 0x90, 0x59, 0x03, 0xaa, 0x32, 0xe4,
	0xe8, 0x2b, 0x89, 0x1d, 0x3f, 0x08, 0x50, 0xd7, 0xce, 0xb4, 0xab, 0xb2, 0x57, 0x49, 0x86, 0xf7,
	0x41, 0x80, 0xec, 0x08, 0x4a, 0x33, 0xa2, 0xce, 0x04, 0x87, 0x7a, 0x3e, 0x86, 0x8b, 0x33, 0xa2,
	0x36, 0x0e, 0x99, 0x0e, 0xa5, 0x29, 0x47, 0x1a, 0xc8, 0xb1, 0x5e, 0x88, 0x81, 0xe4, 0x6a, 0x19,
	0xa0, 0xa7, 0x77, 0x79, 0x9c, 0x42, 0x39, 0x26, 0x6e, 0xdd, 0x02, 0x73, 0x49, 0xb4, 0xc7, 0xf8,
	0xef, 0x97, 0x58, 0x27, 0x60, 0x64, 0xa5, 0x5b, 0xe3, 0x16, 0x54, 0x5c, 0x12, 0x8f, 0xdc, 0x47,
	0xd5, 0xe5, 0xbe, 0xfa, 0x9b, 0x65, 0x1d, 0x6a, 0x3f, 0x45, 0x89, 0xd9, 0xcd, 0x22, 0x0f, 0x05,
	0x97, 0x04, 0x7b, 0x82, 0xea, 0x6e, 0x64, 0xa7, 0xf6, 0x4e, 0xd8, 0x76, 0xfa, 0x9f, 0xc6, 0xe5,
	0x1e, 0x42, 0xb2, 0x82, 0x75, 0xe0, 0x20, 0x9d, 0xc2, 0x79, 0x56, 0x9b, 0xa2, 0x18, 0xd7, 0x7b,
	0x29, 0xdb, 0x05, 0x2e, 0x94, 0xbf, 0xd3, 0x38, 0xce, 0xea, 0xb6, 0xa0, 0xd1, 0xf8, 0x05, 0x4c,
	0xec, 0x1e, 0xee, 0x5e, 0x57, 0xa6, 0xb6, 0x5c, 0x99, 0xda, 0xfb, 0xca, 0xd4, 0x16, 0x6b, 0x33,
	0xb7, 0x5c, 0x9b, 0xb9, 0xb7, 0xb5, 0x99, 0x7b, 0xbe, 0x10, 0x03, 0xd5, 0x9f, 0x74, 0xed, 0x9e,
	0x1c, 0x39, 0xa3, 0x48, 0xf5, 0x39, 0xa2, 0xef, 0xc4, 0x5d, 0x9d, 0x7f, 0xb5, 0x55, 0x45, 0x21,
	0xa7, 0x6e, 0x31, 0x6e, 0x62, 0xeb, 0x23, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x21, 0x42, 0x5e, 0xc8,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RegisterRelay registers (or replaces) the calling validator's relay endpoint.
	RegisterRelay(ctx context.Context, in *MsgRegisterRelay, opts ...grpc.CallOption) (*MsgRegisterRelayResponse, error)
	// UnregisterRelay removes the calling validator's relay endpoint.
	UnregisterRelay(ctx context.Context, in *MsgUnregisterRelay, opts ...grpc.CallOption) (*MsgUnregisterRelayResponse, error)
	// Heartbeat updates the LastHeartbeat timestamp on an existing endpoint.
	Heartbeat(ctx context.Context, in *MsgHeartbeat, opts ...grpc.CallOption) (*MsgHeartbeatResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterRelay(ctx context.Context, in *MsgRegisterRelay, opts ...grpc.CallOption) (*MsgRegisterRelayResponse, error) {
	out := new(MsgRegisterRelayResponse)
	err := c.cc.Invoke(ctx, "/mytc.relay.v1.Msg/RegisterRelay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnregisterRelay(ctx context.Context, in *MsgUnregisterRelay, opts ...grpc.CallOption) (*MsgUnregisterRelayResponse, error) {
	out := new(MsgUnregisterRelayResponse)
	err := c.cc.Invoke(ctx, "/mytc.relay.v1.Msg/UnregisterRelay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Heartbeat(ctx context.Context, in *MsgHeartbeat, opts ...grpc.CallOption) (*MsgHeartbeatResponse, error) {
	out := new(MsgHeartbeatResponse)
	err := c.cc.Invoke(ctx, "/mytc.relay.v1.Msg/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RegisterRelay registers (or replaces) the calling validator's relay endpoint.
	RegisterRelay(context.Context, *MsgRegisterRelay) (*MsgRegisterRelayResponse, error)
	// UnregisterRelay removes the calling validator's relay endpoint.
	UnregisterRelay(context.Context, *MsgUnregisterRelay) (*MsgUnregisterRelayResponse, error)
	// Heartbeat updates the LastHeartbeat timestamp on an existing endpoint.
	Heartbeat(context.Context, *MsgHeartbeat) (*MsgHeartbeatResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterRelay(ctx context.Context, req *MsgRegisterRelay) (*MsgRegisterRelayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterRelay not implemented")
}
func (*UnimplementedMsgServer) UnregisterRelay(ctx context.Context, req *MsgUnregisterRelay) (*MsgUnregisterRelayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterRelay not implemented")
}
func (*UnimplementedMsgServer) Heartbeat(ctx context.Context, req *MsgHeartbeat) (*MsgHeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterRelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterRelay)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterRelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mytc.relay.v1.Msg/RegisterRelay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterRelay(ctx, req.(*MsgRegisterRelay))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnregisterRelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnregisterRelay)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnregisterRelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mytc.relay.v1.Msg/UnregisterRelay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnregisterRelay(ctx, req.(*MsgUnregisterRelay))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgHeartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mytc.relay.v1.Msg/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Heartbeat(ctx, req.(*MsgHeartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mytc.relay.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterRelay",
			Handler:    _Msg_RegisterRelay_Handler,
		},
		{
			MethodName: "UnregisterRelay",
			Handler:    _Msg_UnregisterRelay_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Msg_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mytc/relay/v1/tx.proto",
}

func (m *MsgRegisterRelay) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterRelay) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterRelay) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.WssUrl) > 0 {
		i -= len(m.WssUrl)
		copy(dAtA[i:], m.WssUrl)
		i = encodeVarintTx(dAtA, i, uint64(len(m.WssUrl)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OperatorAddr) > 0 {
		i -= len(m.OperatorAddr)
		copy(dAtA[i:], m.OperatorAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OperatorAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterRelayResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterRelayResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterRelayResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUnregisterRelay) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnregisterRelay) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnregisterRelay) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OperatorAddr) > 0 {
		i -= len(m.OperatorAddr)
		copy(dAtA[i:], m.OperatorAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OperatorAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUnregisterRelayResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnregisterRelayResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnregisterRelayResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgHeartbeat) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgHeartbeat) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgHeartbeat) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OperatorAddr) > 0 {
		i -= len(m.OperatorAddr)
		copy(dAtA[i:], m.OperatorAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OperatorAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgHeartbeatResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgHeartbeatResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgHeartbeatResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterRelay) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.WssUrl)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterRelayResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUnregisterRelay) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUnregisterRelayResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgHeartbeat) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgHeartbeatResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterRelay) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterRelay: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterRelay: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WssUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WssUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterRelayResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterRelayResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterRelayResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnregisterRelay) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnregisterRelay: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnregisterRelay: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnregisterRelayResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnregisterRelayResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnregisterRelayResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgHeartbeat) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgHeartbeat: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgHeartbeat: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgHeartbeatResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgHeartbeatResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgHeartbeatResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
